In [1]:
# from utils.environment import GridWorld
# import numpy as np

In [2]:
# env = GridWorld()


In [49]:
# _,r,done = env.step(np.array([0,0,0,0]))

# for i in range(4):
#     row = env.state[i] // 30
#     column = env.state[i] % 30

#     print("element", env.state[i], "row", row, "column", column)

# print("Reward:  ", r, "Done", done)


element 389 row 12 column 29
element 389 row 12 column 29
element 389 row 12 column 29
element 389 row 12 column 29
Reward:  40 Done True


In [30]:
import itertools
import numpy as np

# Calculate "8 choose 4"
n = 8
k = 4
combinations = list(itertools.combinations(range(n), k))

# Initialize an empty array to store the combinations
combinations_array = np.zeros((len(combinations), n), dtype=int)

# Fill the array with combinations
for i, comb in enumerate(combinations):
    combinations_array[i, comb] = 1

first = combinations_array.copy()
second = combinations_array.copy()
third = combinations_array.copy()
fourth = combinations_array.copy()

i = 0

for row in first:

    index_1, index_2, index_3, index_4 = np.where(row == 1)[0]

    first[i,index_1] = 2
    second[i,index_2] = 2
    third[i,index_3] = 2
    fourth[i,index_4] = 2

    i += 1


# Print the array of combinations
print(np.shape(first))

print(first)


print("second")
print(second)



(70, 8)
[[2 1 1 1 0 0 0 0]
 [2 1 1 0 1 0 0 0]
 [2 1 1 0 0 1 0 0]
 [2 1 1 0 0 0 1 0]
 [2 1 1 0 0 0 0 1]
 [2 1 0 1 1 0 0 0]
 [2 1 0 1 0 1 0 0]
 [2 1 0 1 0 0 1 0]
 [2 1 0 1 0 0 0 1]
 [2 1 0 0 1 1 0 0]
 [2 1 0 0 1 0 1 0]
 [2 1 0 0 1 0 0 1]
 [2 1 0 0 0 1 1 0]
 [2 1 0 0 0 1 0 1]
 [2 1 0 0 0 0 1 1]
 [2 0 1 1 1 0 0 0]
 [2 0 1 1 0 1 0 0]
 [2 0 1 1 0 0 1 0]
 [2 0 1 1 0 0 0 1]
 [2 0 1 0 1 1 0 0]
 [2 0 1 0 1 0 1 0]
 [2 0 1 0 1 0 0 1]
 [2 0 1 0 0 1 1 0]
 [2 0 1 0 0 1 0 1]
 [2 0 1 0 0 0 1 1]
 [2 0 0 1 1 1 0 0]
 [2 0 0 1 1 0 1 0]
 [2 0 0 1 1 0 0 1]
 [2 0 0 1 0 1 1 0]
 [2 0 0 1 0 1 0 1]
 [2 0 0 1 0 0 1 1]
 [2 0 0 0 1 1 1 0]
 [2 0 0 0 1 1 0 1]
 [2 0 0 0 1 0 1 1]
 [2 0 0 0 0 1 1 1]
 [0 2 1 1 1 0 0 0]
 [0 2 1 1 0 1 0 0]
 [0 2 1 1 0 0 1 0]
 [0 2 1 1 0 0 0 1]
 [0 2 1 0 1 1 0 0]
 [0 2 1 0 1 0 1 0]
 [0 2 1 0 1 0 0 1]
 [0 2 1 0 0 1 1 0]
 [0 2 1 0 0 1 0 1]
 [0 2 1 0 0 0 1 1]
 [0 2 0 1 1 1 0 0]
 [0 2 0 1 1 0 1 0]
 [0 2 0 1 1 0 0 1]
 [0 2 0 1 0 1 1 0]
 [0 2 0 1 0 1 0 1]
 [0 2 0 1 0 0 1 1]
 [0 2 0 0 1 1 1 0]
 [0 

In [24]:
a = np.array([1,2,3,2])

a==2

array([False,  True, False,  True])